### PR TITLE
move roughjs to npm dependencies

### PR DESCRIPTION
**Pull request by linkstrifer**

### CODE REVIEW

**Comment by linkstrifer** [comment]
Tried to update to v0.2.2 and found this issue

**Comment by pshihn** [comment]
Can you explain what issue you are running into?  You do not need roughjs installed for rough-notation to work . rough-notation bundles in a few function it copies from roughjs, so it's a dev time dependency.

**Comment by linkstrifer** [comment]
Without roughjs as a dependency, I have some unresolved dependencies

`math` and `renderer` from roughjs

Hyper 6_5_2020 20_27_41

**Comment by pshihn** [comment]
I think because you are importing raw files in your project rather than the built modules. I should not be shipping intermediate files anyway. 

i.e should not import `rough-notation/lib/rough-notation` but just from `rough-notation`

I really don't think you would need roughjs because the built output already has all the code from roughjs.

**Comment by pshihn** [comment]
I have create a pull request in your project addressing this issue: https://github.com/linkstrifer/react-rough-notation/pull/7 Let me know if that works for you.

**Comment by linkstrifer** [comment]
You are totally right, thanks for the fix!

**Pull request closed without merging**
